// index, show, store, update, destroy
const Rating = require('../models/Rating')
const User = require('../models/User')
const Content = require('../models/Content')

module.exports = {
  

  async index(req, res){

    const content_id = req.query.content_id

    const ratings = await Rating.find({content: content_id })

    return res.json(ratings)

  },


  async store(req, res){

// _id	String	automatically generated by MongoDB
// user	user._id	user that added the rate
// content	content._id	content rated
// rate	number	0.0 to 5.0
// comment	String	comment to the rate
// dateCreated	String	created date

    const { content_id, rate, comment } = req.body

    const { user_id } = req.headers

    const user = await User.findById(user_id)

    const content = await Content.findById(content_id)

    if (!user){
      return res.status(400).json({error: 'User does not exist!'})
    }

    if (!content){
      return res.status(400).json({error: 'Content does not exist!'})
    }

    const rating = await Rating.create({
      user: user_id,
      content: content_id,
      rate,
      comment,
    })

    const contentQntRate = content.qntRate + 1 
    const contentTotalRate = (content.ratings + rate) / contentQntRate

    await Content.updateOne({_id: content_id}, {totalRate : contentTotalRate, qntRate: contentQntRate})

    return res.json(rating)
  }
}