const mongoose = require('mongoose')

// _id	String	automatically generated by MongoDB
// playslist	boolean	Playlist on single video
// ytID	String	Youtube ID
// user	user._id	user that added the list/video on the platform
// title	String	got from first video
// tags	Array<String>	tags that the video is related
// totalRate	number	Average rate, updated with a new rating
// dateCreated	String	created date

const contentSchema = new mongoose.Schema({
  date     : String,
  approved : Boolean,

  playslist     : {

      type : Boolean,
      ref  : 'Playslist',
  
  },

  ytID     : {

    type : String,
    ref  : 'YtID',

  },

  user     : {

    type : mongoose.Types.ObjectId,
    ref  : 'User',

  },

  title     : {

    type : String,
    ref  : 'Title',

  },

  tags     : {
    
    type : [String],
    ref  : 'Tags',
    
  },

  totalRate     : {
    
    type : Number,
    ref  : 'TotalRate',
    
  },
  
  dateCreated     : {

    type : Date,
    default: Date.now(),
    ref  : 'DateCreated',

  },


})

module.exports = mongoose.model('Content', contentSchema)


