const mongoose = require('mongoose')

// _id	String	automatically generated by MongoDB
// user	user._id	user that added the rate
// content	content._id	content rated
// rate	number	0.0 to 5.0
// comment	String	comment to the rate
// dateCreated	String	created date

const userSchema = new mongoose.Schema({
  date     : String,
  approved : Boolean,

  user     : {

    type : mongoose.Types.ObjectId,
    ref  : 'User',

  },

  content     : {

    type : mongoose.Types.ObjectId,
    ref  : 'Content',

  },

  rate     : {

    type : Number,
    ref  : 'Rate',

  },

  comment     : {

    type : String,
    ref  : 'Comment',

  },
  
  
  dateCreated     : {

    type : Date,
    default: Date.now(),
    ref  : 'DateCreated',

  },



})

module.exports = mongoose.model('User', userSchema)


