const mongoose = require('mongoose')

// _id	String	automatically generated by MongoDB
// googleId	String	from GoogleApi
// imageUrl	String	from GoogleApi
// email	String	from GoogleApi
// name	String	from GoogleApi
// screenName	String	created on first login
// favorites	[ObjectId]	favorite contents
// dateCreated	String	created date

const userSchema = new mongoose.Schema({
  date     : String,
  approved : Boolean,

  googleId     : {

      type : String,
      ref  : 'GoogleID',
  
  },

  imageUrl     : {

    type : String,
    ref  : 'ImageUrl',

  },

  email     : {

    type : String,
    ref  : 'Email',

  },

  screenName     : {

    type : String,
    ref  : 'ScreenName',

  },
  
  
  favorites     : {
    
    type : [mongoose.Types.ObjectId],
    ref  : 'Favorites',
    
  },
  
  dateCreated     : {

    type : Date,
    default: Date.now(),
    ref  : 'DateCreated',

  },



})

module.exports = mongoose.model('User', userSchema)


